### ISSUE TITLE
issues with standard headers

### ISSUE THREAD

**Issue by nickdesaulniers** [xaizek/vim-inccomplete#3]
I was not able to autocomplete `#include <chrono>` or `#include <thread>` or even `#include <iostream>`.  The listed headers seem to only be from `/usr/include/*`.

**Comment by nickdesaulniers** [comment]
For instance, should the include path be the same as the output from `clang -x c++ -v -E /dev/null`?

**Comment by xaizek** [comment]
See [list of sources](https://github.com/xaizek/vim-inccomplete/blob/d26269b98bd0606c1cb7a661890c2d9df21eb1fd/doc/inccomplete.txt#L35-L39). `clang_complete` used to run `g++/clang++ -x c++ -v -E /dev/null`, which output was put into `b:clang_user_options` so everything worked fine, I'm not sure if still works equally well these days.

You could list output of the command in `g:clang_user_options` by prefixing each directory with `-I` for now. I'll add an option to set compiler invocation string, empty by default, I keep putting this off over and over again (stopped relying on automatic completion that much).

**Comment by nickdesaulniers** [comment]
should they be space separated? ex `g:clang_user_options -I /usr/include/c++/4.2.1 -I /usr/include/c++/4.2.1/backward -I /usr/local/include -I /usr/local/bin/../lib/clang/3.7.0/include -I /usr/include -I /System/Library/Frameworks -I /Library/Frameworks`

What's the difference between `b:clang_user_options` and `g:clang_user_options`?

**Comment by xaizek** [comment]
It's command-line arguments, so space after `-I` is optional, but arguments should be separated, e.g.
```vim
    let g:clang_user_options = '-I/usr/local/include/'
    let g:clang_user_options .= ' -I/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/include/'
    let g:clang_user_options .= ' -I/usr/include/c++/4.8.2/x86_64-slackware-linux/'
    let g:clang_user_options .= ' -I/usr/include/c++/4.8.2/'
```
`g:` prefixes global variables, `b:` denotes variables that are local to buffer, you won't set them easily from `vimrc` (need to be in context of a buffer, there are autocommands and files under `ftplugin/` for that).

**Comment by nickdesaulniers** [comment]
Thanks for the help so far, but I still seem to be unable to autocomplete things like iostream and chrono.  From the bottom of my [~/.vimrc file](http://pastebin.mozilla.org/8642322).

**Comment by xaizek** [comment]
There was check for both buffer and global clang_complete variables at the same time, so `g:clang_user_options` wasn't parsed without clang_complete being active. Thanks, should work with the latest commit.

**Comment by nickdesaulniers** [comment]
Beautiful, thank you!  For any who might stumble on this thread in the future, I was running an older version of OSX (10.8.5) so I need to run `clang++ -x c++ -v -E /dev/null -stdlib=libc++` to get the paths for chrono and thread, due to [some arcana](http://stackoverflow.com/a/14657009/1027966).  See [this commit](https://github.com/nickdesaulniers/dotfiles/commit/81a88f0109ea52de301e00753afe19e85c6a067f).
