### ISSUE TITLE
Why completion after `#include "` doesn't consider paths provided by `clang_options`?

### ISSUE THREAD

**Issue by htfy96** [xaizek/vim-inccomplete#4]
> 
> "" Completion~
> 
> For "" it gets all header files in the current directory or any relative
> to it directory.

```
/
|--- /include
|--- /src
|    |--- foo.cpp
|--- /third-party
|    |--- /libbar
|         |--- /include
|              |--- bar.hpp
|--- .clang
|--- CMakeLists.txt
```
It's a typical implementation that the path `third-party/libbar/include` is added to `-I` in `CMakeLists.txt` so that `#include "bar.hpp"` would be a valid sentence in `src/foo.cpp`. However in current version completion after `#include "` doesn't consider paths provided by `b:clang_options`.

**Comment by xaizek** [comment]
`-I` options are used for `<>`-completion to provide system-wide paths as well, it would be wrong to use them in `""`. The issue is that one can't differentiate between system and local headers, so there would need to be a different option for that, not clang-specific.
