### ISSUE TITLE
Support for vim-clang

### ISSUE THREAD

**Issue by stefanos82** [xaizek/vim-inccomplete#6]
Hey @xaizek, I have had some issues with `clang_complete`s performance; it was too slow for large projects and decided to try something lighter, that does not use Python to parse every single file for auto-completion.

I have found `vim-clang` and I have found it lighter than `clang_complete`, even though it uses `clang` binary for auto-completion.

I wanted to ask: is it possible to support it? I have managed to use `<>`, but double quotes don't work at all.

The project uses `.clang` files, much like `.clang_complete`.

Would it be a difficult task?

**Comment by xaizek** [comment]
Hi. Have no idea how difficult it might actually be, but I see `b:clang_options` variable. I think you can try handling it [here](https://github.com/xaizek/vim-inccomplete/blob/170fd0d70e1727af7a9fecdf8120517f6d7ea100/plugin/inccomplete.vim#L498-L500) below current if-statement by adding this:
```vim
    if a:which != 0 && exists('b:clang_options')
        let l:opts .= b:clang_options.' '
    endif
```
If include completion works after that, then it's easy :-)
